spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/desafioCep?authSource=admin
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  cloud:
    openfeign:
      lazy-attributes-resolution: true

  security:
    user:
      name: admin
      password: 123456

  cep:
    api:
      url: https://viacep.com.br/ws